name: EntiGuard
version: 0.1
main: net.amigocraft.entiguard.EntiGuard
author: Maxim Roncace
description: Mob armies!
permissions:
  entiguard.recruit:
    description: Allows recruitment of mobs
    default: true
  entiguard.unlimited:
    description: Allows armies larger than configured maximum size
    default: op